FROM ubuntu:16.10

RUN apt-get update && apt-get install -y --no-install-recommends \
    texlive \
    texlive-lang-german \
    texlive-lang-english \
    texlive-font-utils \
    texlive-generic-recommended \
    texlive-fonts-recommended \
    texlive-fonts-extra \
    texlive-formats-extra \
    texlive-latex-recommended \
    texlive-latex-extra \
    texlive-science \
  && apt-get clean
